//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesApp1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Linq;
    using System.Data.Entity;

    public partial class Merchandise
    {
        public int productid { get; set; }

        public string make { get; set; }

        public string style { get; set; }

        public Nullable<double> price { get; set; }

        public string engine { get; set; }

        public string imageURL { get; set; }

        public string description { get; set; }


        public Merchandise()
        {


        }
        public Merchandise(int productid, string make, string style, double price, string engine, string imageURL, string description)
        {
            this.productid = 104;
            this.make = make;
            this.style = style;
            this.price = price;
            this.engine = engine;
            this.imageURL = imageURL;
            this.description = description;
        }

        public override string ToString()
        {
            return " make: " + make + ", style: " + style + ", price " + price
                + ",engine: " + engine + ", imageURL: " + imageURL + ", description : " + description;
        }
    }
}

