//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CarSalesApp1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Data.Entity;

    public partial class User
    {
        [Required(ErrorMessage = "Username is required")]

        [StringLength(50, MinimumLength = 4)]
        public string username { get; set; }
        [Required(ErrorMessage = "Name is required")]

        [StringLength(50, MinimumLength = 4)]
        public string name { get; set; }
        [Required(ErrorMessage = "Last Name is required")]

        [StringLength(50, MinimumLength = 4)]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Password is required")]

        [StringLength(50, MinimumLength = 4)]
        public string password { get; set; }
        public User()
        {

        }
        public User(string username, string name, string lastName, string password)
        {

            this.username = username;
            this.name = name;
            this.lastName = lastName;
            this.password = password;

        }

    }
}
